// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'app_widget.dart';

List<RouteEntity> get routes => [
  RouteEntity(
    key: '/comments/[id]/comments',
    uri: Uri.parse('/comments/[id]/comments'),
    routeBuilder: b0Builder,
  ),
  RouteEntity(
    key: '/signup',
    uri: Uri.parse('/signup'),
    routeBuilder: b1Builder,
  ),
  RouteEntity(key: '/reset', uri: Uri.parse('/reset'), routeBuilder: b2Builder),
  RouteEntity(key: '/login', uri: Uri.parse('/login'), routeBuilder: b3Builder),
  RouteEntity(
    key: '/internal/home',
    parent: '/internal',
    uri: Uri.parse('/internal/home'),
    routeBuilder: b4Builder,
  ),
  RouteEntity(
    key: '/internal',
    uri: Uri.parse('/internal'),
    routeBuilder: b5Builder,
  ),
  RouteEntity(key: '/', uri: Uri.parse('/'), routeBuilder: b6Builder),
];

const routePaths = (
  path: '/',
  comments: (
    path: '/comments',
    $id: (path: '/comments/[id]', comments: '/comments/[id]/comments'),
  ),
  signup: '/signup',
  reset: '/reset',
  login: '/login',
  internal: (path: '/internal', home: '/internal/home'),
);
