// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'app_widget.dart';

List<RouteEntity> get routes => [
  RouteEntity(
    key: '/comments/[id]/comments',
    uri: Uri.parse('/comments/[id]/comments'),
    routeBuilder: b0Builder,
  ),
  RouteEntity(
    key: '/user_details',
    uri: Uri.parse('/user_details'),
    routeBuilder: b1Builder,
  ),
  RouteEntity(
    key: '/signup',
    uri: Uri.parse('/signup'),
    routeBuilder: b2Builder,
  ),
  RouteEntity(key: '/reset', uri: Uri.parse('/reset'), routeBuilder: b3Builder),
  RouteEntity(key: '/login', uri: Uri.parse('/login'), routeBuilder: b4Builder),
  RouteEntity(
    key: '/internal/home',
    parent: '/internal',
    uri: Uri.parse('/internal/home'),
    routeBuilder: b5Builder,
  ),
  RouteEntity(
    key: '/internal',
    uri: Uri.parse('/internal'),
    routeBuilder: b6Builder,
  ),
  RouteEntity(
    key: '/internal/aggregate_events',
    parent: '/internal',
    uri: Uri.parse('/internal/aggregate_events'),
    routeBuilder: b7Builder,
  ),
  RouteEntity(
    key: '/internal/add_events',
    parent: '/internal',
    uri: Uri.parse('/internal/add_events'),
    routeBuilder: b8Builder,
  ),
  RouteEntity(key: '/', uri: Uri.parse('/'), routeBuilder: b9Builder),
];

const routePaths = (
  path: '/',
  comments: (
    path: '/comments',
    $id: (path: '/comments/[id]', comments: '/comments/[id]/comments'),
  ),
  userDetails: '/user_details',
  signup: '/signup',
  reset: '/reset',
  login: '/login',
  internal: (
    path: '/internal',
    home: '/internal/home',
    aggregateEvents: '/internal/aggregate_events',
    addEvents: '/internal/add_events',
  ),
);
