// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'app_widget.dart';

List<RouteEntity> get routes => [
  RouteEntity(
    key: '/signup',
    uri: Uri.parse('/signup'),
    routeBuilder: b0Builder,
  ),
  RouteEntity(key: '/reset', uri: Uri.parse('/reset'), routeBuilder: b1Builder),
  RouteEntity(key: '/login', uri: Uri.parse('/login'), routeBuilder: b2Builder),
  RouteEntity(
    key: '/internal/home',
    parent: '/internal',
    uri: Uri.parse('/internal/home'),
    routeBuilder: b3Builder,
  ),
  RouteEntity(
    key: '/internal',
    uri: Uri.parse('/internal'),
    routeBuilder: b4Builder,
  ),
  RouteEntity(key: '/', uri: Uri.parse('/'), routeBuilder: b5Builder),
];

const routePaths = (
  path: '/',
  signup: '/signup',
  reset: '/reset',
  login: '/login',
  internal: (path: '/internal', home: '/internal/home'),
);
